name: pomodoro_timer
description: A simple and minimalist Pomodoro Timer app for students and workers
publish_to: 'none'
version: 1.0.2+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.5.4
  
  # Notifications
  flutter_local_notifications: ^19.0.0

  # Timezone (for scheduled notifications)
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  
  # Vibration
  vibration: ^3.0.0
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Ads
  google_mobile_ads: ^5.2.0
  
  # Device info
  device_info_plus: ^11.2.0
  
  # Icon
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # i18n JSON files
  assets:
    - assets/l10n/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/pomodoro_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/pomodoro_icon.png"
